services:
  - type: web
    name: groq-fastapi-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false  # will be set manually in Render dashboard
